### ISSUE TITLE
Problems with HeliTrim.lua

### ISSUE THREAD

**Issue by BlaineElMono** [X-Friese/FlyWithLua#40]
Hello
I have problems with FlyWithLua_NG_v2.7 with the script HeliTrim.lua
Automatically moves to the Scripts folder (Quarantine)
How do I know what the problem is?

**Comment by sparker256** [comment]
I just tested with the current version 2.7.16 and do not see your issue.

**Comment by BlaineElMono** [comment]
Thank you for your reply.
Look for the problem in the log.txt file and find the problem:

- _### FlyWithLua Info: Start loading script file D:\Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/HeliTrim.lua
- FlyWithLua Error: The variable "xp_psi" is still defined as DataRef "sim/cockpit2/gauges/indicators/heading_electric_deg_mag_pilot".
- FlyWithLua Info: Finished loading script file D:\Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/HeliTrim.lua
- FlyWithLua Error: The error seems to be inside of script file D:\Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/HeliTrim.lua
- FlyWithLua Info: Moved Bad Script to D:\Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts (Quarantine)/HeliTrim.lua_


Apparently another script uses the same variable and they were in conflict.
Simply rename the variable and it's fixed.
Thank you!

**Comment by sparker256** [comment]
This issue has been resolved.
