### ISSUE TITLE
HeliTrim.lua disables joystick curves when tweak is active

### ISSUE THREAD

**Issue by d41k4n** [X-Friese/FlyWithLua#48]
Using X-Plane 11.34: Whenever the HeliTrim tweak is active any configured joystick curves are no longer applied (input behaves as if curves are cleared i.e. full-range linear). Disabling the tweak brings everything back to normal. Would be great if any configured curves remained applied while the tweak is on. ﻿

Tested with plugin version v2.7.18

**Comment by d41k4n** [comment]
A possible fix is available [here](https://forums.x-plane.org/index.php?/forums/topic/165224-helitrim-tweak-disables-joystick-curves/&do=findComment&comment=1706575).

**Comment by sparker256** [comment]
Updated HeliTrim script Version: 1.2 to resolve issue.
