### ISSUE TITLE
path

### ISSUE THREAD

**Issue by DemonRem** [X-Friese/FlyWithLua#5]
I sorry but I new with lua , what is the mean of it I try a lot of shit to fix it

 Can't read out the subfolder given to function directory_to_table().

I create folder 3jCabin-sounds/soundset   didn't work
I try to put the wav files with the script yet not work

help me please

**Comment by X-Friese** [comment]
Please use the help forum at x-plane.org, this is for developer discussing the code of FlyWithLua. You will get no end user support here.
