### ISSUE TITLE
Mouse functions not working in VR

### ISSUE THREAD

**Issue by AfromD** [X-Friese/FlyWithLua#50]
When in VR view, the functions do_on_mouse_wheel() and do_on_mouse_click() do not work. Additionally, MOUSE_X and MOUSE_Y are not updated.

I have tried working with sim/graphics/view/click_3d_x and sim/graphics/view/click_3d_y, but they also change on head movement, I guess because of parallax effects where the mouse pointer hovers over the texture. If you look at it from another angle, it hovers over something else. So it is a composite of head position, head distance from the pointer, and mouse position. And I haven't found any alternative way to register clicks.

**Comment by sparker256** [comment]
Been a bit busy and trying to catch up with issues.

For FlyWithLua to work correctly in VR you need to use either Floating Windows section 17 of the manual or Imgui Windows section 18 of the manual.

**Comment by AfromD** [comment]
I am trying to detect mouse movement or clicks, for automatically activating the VR mouse. For that, I would need above functions. So I am not trying to display anything.

I am working on processing 3d_mouse coords, but it is extremely cumbersome, because they reflect not only mouse position, but also camera position and the 3d model.

I think one can get mouse coordinates to be derived by using OpenGL, but that is not accessible from lua. It would need a plugin for that. 

I see Flywithlua now uses a 2d window to catch mouse events. Would changing to XPLMGetMouseLocationGlobal would be of any help, since then the mouse doesn't have to be over the window?

**Comment by sparker256** [comment]
The function XPLMGetMouseLocationGlobal works with windows so not sure if that will give you what you are looking for. https://developer.x-plane.com/sdk/XPLMGetMouseLocationGlobal/ There is also a script floating_wnd_new_XPLM_methods.lua found in Resources/plugins/FlyWithLua/Scripts (disabled) that shows that function.

Another option is to map a joystick button to the command sim/VR/toggle_3d_mouse_cursor

A second option is to create a script that has a button on it that would execute the same command.

**Comment by sparker256** [comment]
Lack of activity.
