### ISSUE TITLE
Copyright Violation in src/FloatingWindows/ImGUIIntegration.h and src/FloatingWindows/ImGUIIntegration.cpp

### ISSUE THREAD

**Issue by kuroneko** [X-Friese/FlyWithLua#55]
I'm the original author of the xsb_public "[ImgWindow.cpp](https://github.com/kuroneko/xsb_public/blob/master/ImgWindow.cpp)" and "[ImgWindow.h](https://github.com/kuroneko/xsb_public/blob/master/ImgWindow.h)" of which these files are clearly derived as told by the identical functions containing identical comments and naming practices where code was retained in the ImGUIIntegration.cpp file.

The original code was published under the LGPL, and whilst rights to produce derivatives were granted, it required the maintenance of copyright notices and adherence to the LGPL.

I have since publicly posted permission for derivations to obey the BSD 3 Clause in lieu of the LGPL.  (see https://forums.x-plane.org/index.php?/forums/topic/198665-x-plane-imgui-bindings-copyright-violations/ ).

Please fix your source to comply with one of the two permitted licenses.

**Comment by sparker256** [comment]
As per the discussions on the org you have linked here are we now good or do you still something from us to not be a Copyright Violation.

I am now the head of development and the original author wanted me to make sure I get this fixed so that is what I am trying to do.

**Comment by sparker256** [comment]
Can this now be closed?

**Comment by kuroneko** [comment]
Looks good, thanks.
