### ISSUE TITLE
Integration of LUAFILESYSTEM

### ISSUE THREAD

**Issue by urbanswelt** [X-Friese/FlyWithLua#58]
Hi Sparker,
in one of my next projects I will use LFS to create a subfolder for my data/scripts in the script folder. This one I would have to deliver every time to the users.

It would be great if we could take this into the standard modules.
I have tested this on MacOs. (paste copy -->happy)

Best regards Lars

Source:
luafilesystem via LuaJIT FFI with unicode facilities
https://github.com/sonoro1234/luafilesystem
--> lfs.lua --> lfs_ffi.lua

**Comment by sparker256** [comment]
I am not following what you are trying to do and do not see a fork that I can look at.

**Comment by urbanswelt** [comment]
Hi Sparker,
Hello, Sparker,

sorry it was kind of late at my place.
It would be very helpful if we could include LUAFILESYSTEM in our modules.

Is there anything wrong with that? 
The great thing is that we only have to include the LUA files.

Thank you very much !
Greetings Lars

**Comment by sparker256** [comment]
I need details that you have so far not provided.

Either create a fork of FlyWithLua that I can look at your changes or attach a zip of your working version on your Mac.

I just need to be very sure that we will not be breaking what is currently working.

Thanks Bill

**Comment by urbanswelt** [comment]
Hi Sparker,

here a zip with a test script + module.
Thanks in advance !

[FlyWithLua_LFS.zip](https://github.com/X-Friese/FlyWithLua/files/4707516/FlyWithLua_LFS.zip)

**Comment by sparker256** [comment]
Thanks looks good to me and will be included in the next version of FlyWithLua.

**Comment by sparker256** [comment]
The current version (2.7.24) has this included.

**Comment by sparker256** [comment]
Since we not have that functionality will close this.
