### ISSUE TITLE
DOCU: 6.1.7 graphics.draw_angle_line( x, y, angle, length ) LineWidth Missing

### ISSUE THREAD

**Issue by urbanswelt** [X-Friese/FlyWithLua#59]
Hello, Sparker,

the documentation has a missing entry for line width Is there an online documentation for a Pull Request ?

![image](https://user-images.githubusercontent.com/2138928/82741098-2a8bbe80-9d4f-11ea-9763-6e898fff1dc2.png)

Original Code

function draw_angle_line(x, y, a, l, w)
    w = w or 1
    local x2
    local y2
    glLineWidth(w)
    x2, y2 = move_angle(x, y, a, l)
    draw_line(x, y, x2, y2)
end

**Comment by sparker256** [comment]
Thanks for pointing out the issue. I have updated my local copy to reflect this change.

**Comment by urbanswelt** [comment]
Ok then we can close this Issue =)
