### ISSUE TITLE
Section 10.1.5 heading doesn't show all arguments

### ISSUE THREAD

**Issue by danapple** [X-Friese/FlyWithLua#62]
The heading of section 10.1.5:
10.1.5 table = XPLMGetDatavf( DataRef )
does not all of the arguments to XPLMGetDatavf(), even though they are listed below.  It should real
10.1.5 table = XPLMGetDatavf( DataRef, inIndex, inMax )

**Comment by sparker256** [comment]
Thanks I have made those changes on my local copy and will be in the next version.

**Comment by sparker256** [comment]
The current has this fixed in the manual.

**Comment by sparker256** [comment]
Since the manual has been updated will close this.

**Comment by danapple** [comment]
Looks good, but just a tiny nit: there are no commas between the arguments.  Seriously, I obsess.

**Comment by sparker256** [comment]
Thanks will be fixed in the next version.
