### ISSUE TITLE
Would like an arc drawing function that doesn't include radial lines

### ISSUE THREAD

**Issue by danapple** [X-Friese/FlyWithLua#63]
The current arc function:
6.1.11 graphics.draw_arc( x, y, start angle, end angle, radius, line width )
draws two radii for the arc, one from the center to the start of the arc and one from the center to the end of the arc.  Sometimes I'd like to draw an arc as part of a unfilled circle that is composed only of the pure arc without the radial line segments.

If this is a defect in graphics.draw_arc, then it could be corrected.  If it is an intentional behavior of the graphics.draw_arc, then it would be very helpful to have a new function, perhaps graphics.draw_pure_arc which draws just the arc without the terminating radii.

Considering that it should be possible to emulate the current behavior using a combination of 
2 calls to graphics.draw_angle_line( x, y, angle, length, line width ) in concert with a pure arc, simply modifying the existing function is compelling, unless that cannot be done for reasons of backward compatibility.

**Comment by urbanswelt** [comment]
Hello, Dan,
Open the graphics.lua inside the folder internals and have a look at this function.
This is a pure "base" implementation by the author himself. You can create pure GL yourself and then make the function available for others ;-)

But trust me GL is not a logical thing ^^

**Comment by sparker256** [comment]
@danapple Have you looked at function draw_arc_line ? Is that what you are looking for because that was added some time ago.

**Comment by danapple** [comment]
Yes, that's exactly what I needed and it works great!  Thanks!
