### ISSUE TITLE
Docu: 18.6 / 17.27 Overlap in heading

### ISSUE THREAD

**Issue by urbanswelt** [X-Friese/FlyWithLua#65]
Hi Sparker,
just a tiny thing =)

![image](https://user-images.githubusercontent.com/2138928/83612479-bdfc9500-a582-11ea-9886-8ee0a35eb6ee.png)

![image](https://user-images.githubusercontent.com/2138928/83613018-788c9780-a583-11ea-9f79-481aa2d8c5ea.png)

Greetings Lars

**Comment by urbanswelt** [comment]
Ohh i see a lot more 17.23 .... looks like a "Global" thing when you create the PDF file =)

**Comment by urbanswelt** [comment]
10.1 Reading classic functions:

strored --> stored ?

![image](https://user-images.githubusercontent.com/2138928/83614802-fbaeed00-a585-11ea-8451-41a47c748b32.png)

**Comment by sparker256** [comment]
I think I have found all the issues and will be in the next release.

**Comment by sparker256** [comment]
This issue has been fixed in the 2.7.25 version so closing this issue.
