### ISSUE TITLE
Documentation is incorrect for X-Plane 11

### ISSUE THREAD

**Issue by shanmoon** [X-Friese/FlyWithLua#8]
The documentation states to go to "Settings > Joystick & Equipment > Buttons: Adv" to assign a custom command to a buttong.

This is incorrect for X-Plane 11. There is no such menu or setting.

**Comment by sparker256** [comment]
I am trying to clean any remaining issues so need to know which manual this is true in.

**Comment by shanmoon** [comment]
I'll look back at the documentation I was reviewing and try to explicitly call it out here by url and/or page #.

**Comment by sparker256** [comment]
Lack of response.
